### ISSUE TITLE
[RFC] Inject alias for chips at config.fish

### ISSUE THREAD

**Issue by simnalamburt** [kinoru/chips#13] opened 2016-04-24 10:19 UTC
Current implementation just injects the line to the config.fish below:

``` fish
# chips (don't touch the line below!)
if [ -e ~/.config/chips/build.fish ] ; source ~/.config/chips/build.fish ; end
```

And current implementation seems to be assuming that chips executable file is located at `~/.local/bin/chips`

``` haskell
-- https://github.com/kinoru/chips/blob/master/src/Lib.hs#L57
execPath <- (byteString <$> getExecutablePath) >>= \ p ->
    if "/ghc" `B.isSuffixOf` p
    then (<> "/.local/bin/chips") . byteString <$> getHomeDirectory
    else return p
```

Then why don't we add the alias for chips at the config.fish? It will provide better default and better UX to the users.

``` fish
# chips (don't touch the lines below!)
alias chips "~/.local/bin/chips; and exec fish"
if [ -e ~/.config/chips/build.fish ]; source ~/.config/chips/build.fish; end
```

**Comment by xtendo-org** [comment] 2016-04-25 01:32
Duplicate of #6. Solved by a0285b6af1b88e3132741ddf6c79c5a2d9c859b3.

**Closed as completed by xtendo-org** 2016-04-25 01:32 UTC
