### ISSUE TITLE
Doesn't work on Sierra

### ISSUE THREAD

**Issue by sargunv** [kinoru/chips#20] opened 2016-07-24 07:47 UTC
I get the following error when trying to run `chips` on the macOS Sierra public beta:

```
fish: 'chips' terminated by signal SIGKILL (Forced quit)
```

**Comment by xtendo-org** [comment] 2016-07-29 19:15
Thanks for the report!

@simnalamburt Do you think you can reproduce this?

**Comment by simnalamburt** [comment] 2016-07-30 07:17
I do not have any spare machine to install macOS Sierra. Help wanted

**Comment by sargunv** [comment] 2016-07-30 07:19
I've never worked with Haskell, but I could try to take a look myself.

**Comment by sargunv** [comment] 2016-07-31 04:08
Having trouble installing Stack via Brew on Sierra. Guess it'll have to wait for Brew or Stack to update to support Sierra.

https://github.com/Homebrew/homebrew-core/issues/1957

**Comment by simnalamburt** [comment] 2016-08-01 05:49
Looks like El Capitan binary is incompatible with Sierra.

**Comment by xtendo-org** [comment] 2016-08-03 05:31
Oh, that explains it. 😃

I'm a full-time GNU/Linux user, but a lot of Haskellers (including the people who make and maintain the Haskell tool chain) definitely use OS X, so I'm sure the switch to macOS will happen pretty quickly once it releases officially.

Until that happens, let's leave this issue open, shall we? 😄 We might soon need to serve three different executable binaries, I guess.

**Comment by xtendo-org** [comment] 2016-10-03 11:32
Hmm.

It seems the binary compatibility should not be the issue? @heejongahn built a macOS Sierra binary, and @simnalamburt confirmed that it works on OS X El Capitan.

**Comment by xtendo-org** [comment] 2016-10-03 14:45
@sargunster The new 1.1.0 release should work on Sierra as well. Could you give it a try?

**Comment by sargunv** [comment] 2016-10-03 15:35
Still getting the error after installing the new version:

```
fish: 'chips' terminated by signal SIGKILL (Forced quit)
```

**Comment by simnalamburt** [comment] 2016-10-03 15:48
@heejongahn and I could not reproduce that error on our macOS machine. Are you still using Sierra public beta or did you upgraded it with official Sierra release?

**Comment by sargunv** [comment] 2016-10-03 15:50
I'm using the official release.

**Comment by xtendo-org** [comment] 2016-10-04 11:51
@sargunster Can you try building 1.1.0 from source with the latest Stack?

**Comment by sargunv** [comment] 2016-10-04 14:01
Building from source works fine. There's a large file size difference between the two binaries:

```
~/.l/bin> ls -l
total 77072
-rwxr-xr-x  1 sargunvohra  staff  35527216 Oct  4 10:00 chips_built
-rwxr-xr-x  1 sargunvohra  staff   3932160 Oct  2 08:14 chips_downloaded
```

**Comment by simnalamburt** [comment] 2016-10-05 11:10
That's correct. We compress chips binaries with [`upx`](https://upx.github.io/)

**Comment by xtendo-org** [comment] 2016-10-05 12:00
The file size difference is probably due to `strip` and `upx` applied for the release binary.

At this point, we don't have enough cases; it could be something that is wrong in both @heejongahn and @simnalamburt's machine, or it could be just @sargunster. Maybe we can detect the root cause by disassembling and analyzing the two binaries, it's a shame I have neither the knowledge nor the tool for that...

Hopefully a plan I already have can address this; As I don't own a macOS machine, releasing chips so far required me asking someone else with an OS X or macOS machine to manually build from source and hand me the binary. This is why I am going to set up a CircleCI-based automatic build for macOS before the next release.

If that build works okay on any macOS machine, everyone can be happy. Until that happens, I apologize for the inconvenience that you have to build from source.

**Comment by nyeong** [comment] 2016-11-13 15:13
I'm using chips, building from source manually, on macOS Sierra(10.12.1).
Maybe the issue have been solved.

**Comment by macowie** [comment] 2016-12-16 17:53
I was also able to build from source and use it just fine, on two machines now, one with 10.12.2 and one on 10.12.1.

**Comment by simnalamburt** [comment] 2017-01-16 07:17
[Chips 1.1.1](https://github.com/xtendo-org/chips/releases/tag/1.1.1) has been released. Now chips should work fine on macOS Sierra.

**Comment by simnalamburt** [comment] 2017-01-21 09:29
Sierra support of chips 1.1.1 and 1.1.2 have been widely tested. I'm closing this issue now. Please mention me if there's any further problem. Thanks! :shipit:

**Closed as completed by simnalamburt** 2017-01-21 09:29 UTC
Labels: help wanted
